version: '2'

services:
  hub:
    build: ../release-notes-hub
    container_name: release-notes-hub
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - "../release-notes-hub:/usr/src/app"
    networks:
      - service
      - public

  mongodb:
    image: mongo
    container_name: release-notes-mongo
    restart: unless-stopped
    volumes:
      - "mongodb_data:/data/db"
      - "mongodb_log:/var/log/mongodb"
    networks:
      - service

networks:
  service:
    driver: bridge
  public:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  mongodb_log:
    driver: local
